#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`transmissions`.

The CLI supports the existing universal-transmission analysis workflow and adds
one documentation helper:

1. Existing analyzer workflow::

       python -m transmissions.cli --spec transmissions/in/spec.json --schedule transmissions/in/schedule.json

2. Sphinx documentation skeleton generation::

       python -m transmissions.cli sphinx-skel transmissions/docs

The ``sphinx-skel`` command generates conservative, GitHub Pages friendly
Sphinx files while preserving the historical no-subcommand analyzer interface.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import sys
from pathlib import Path

try:
    from .apis import list_presets
    from .app import RunRequest, TransmissionApplication, render_text_report
    from .io import load_json
    from .utils import TransmissionAppError, parse_key_value_overrides
except ImportError:  # pragma: no cover - supports flat/script execution
    from apis import list_presets
    from app import RunRequest, TransmissionApplication, render_text_report
    from utils import TransmissionAppError, parse_key_value_overrides

    try:
        from module_loader import load_local_module
    except ImportError:
        from .module_loader import load_local_module  # type: ignore

    _io_mod = load_local_module("io_local", "io.py")
    load_json = _io_mod.load_json


_PACKAGE = "transmissions"
_PROJECT = "Gearsets - transmissions"
_AUTHOR = "Gearsets"

_REQUIRED_MODULES = [
    "transmissions.cli",
    "transmissions.apis",
    "transmissions.app",
    "transmissions.io",
    "transmissions.model",
    "transmissions.utils",
    "transmissions.core.clutch",
    "transmissions.core.planetary",
    "transmissions.core.shaft",
    "transmissions.core.solver",
]

_OPTIONAL_MODULES = [
    "transmissions.module_loader",
    "transmissions.shift_schedule_builder",
    "transmissions.transmission_spec_builder",
    "transmissions.gui_utils_trans",
    "transmissions.gui_log_trans",
    "transmissions.gui_core_trans",
]

_AUTODOC_MOCK_IMPORTS = [
    "dearpygui",
    "dearpygui.dearpygui",
    "matplotlib",
    "matplotlib.pyplot",
    "numpy",
    "pandas",
    "plotly",
    "plotly.graph_objects",
    "rich",
    "rich.console",
    "rich.panel",
    "rich.table",
    "rich.text",
    "scipy",
    "scipy.linalg",
    "scipy.optimize",
    "sympy",
]


# ---------------------------------------------------------------------------
# Sphinx skeleton helpers
# ---------------------------------------------------------------------------

def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when ``module_name`` can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    import still fails because an optional dependency is missing. Sphinx autodoc
    needs modules that import cleanly, so this helper performs the stricter
    import check used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    seen: set[str] = set()
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if mod in seen:
            continue
        seen.add(mod)
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> transmissions -> repository root
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx ``index.rst`` page."""
    title = "Welcome to transmissions's documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "and its dependencies can be imported before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def build_sphinx_parser() -> argparse.ArgumentParser:
    """Build the parser for the ``sphinx-skel`` helper."""
    parser = argparse.ArgumentParser(
        prog="python -m transmissions.cli sphinx-skel",
        description="Create a deploy-safe Sphinx documentation skeleton for transmissions.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    parser.add_argument("dest", type=Path, help="Destination docs directory, for example transmissions/docs.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")
    return parser


def _run_sphinx_skel(argv: list[str] | None = None) -> int:
    """Generate the Sphinx documentation skeleton."""
    parser = build_sphinx_parser()
    args = parser.parse_args(argv)
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


# ---------------------------------------------------------------------------
# Existing analyzer CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    """Build the historical no-subcommand analyzer parser."""
    p = argparse.ArgumentParser(
        prog="python -m transmissions.cli",
        description=(
            "Universal transmission CLI built from JSON topology + shift schedule. "
            "Use 'python -m transmissions.cli sphinx-skel transmissions/docs' "
            "to generate documentation scaffolding."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    p.add_argument("--spec", dest="spec_path", type=str, required=False, help="Path to transmission spec JSON.")
    p.add_argument("--schedule", dest="schedule_path", type=str, required=False, help="Path to shift schedule JSON.")
    p.add_argument("--preset", type=str, help="Optional preset name defined inside the spec JSON.")
    p.add_argument("--state", type=str, default="all", help="State to solve, e.g. all, 4th, Rev.")
    p.add_argument("--input-speed", type=float, default=1.0, help="Input speed for normalization/reporting.")

    p.add_argument("--show-speeds", action="store_true", help="Show member speeds.")
    p.add_argument("--ratios-only", action="store_true", help="Print condensed ratio table only.")
    p.add_argument("--show-topology", action="store_true", help="Print topology summary.")
    p.add_argument("--as-json", action="store_true", help="Print result payload as JSON.")
    p.add_argument("--out-json", dest="output_json", type=str, help="Optional output JSON path.")

    p.add_argument(
        "--set",
        dest="overrides",
        metavar="KEY=VALUE",
        nargs="*",
        default=[],
        help=(
            "Override spec values. Supported forms: "
            "P1.Ns=48 P1.Nr=96 gearsets.P1.Ns=48 gearsets.P1.Nr=96 "
            "input_member=input output_member=output strict_geometry=true"
        ),
    )

    p.add_argument("--list-presets", action="store_true", help="List spec-defined presets and exit.")
    return p


def _print_presets(spec_path: str | None) -> int:
    """Print presets defined in a transmission spec JSON file."""
    if not spec_path:
        print("ERROR: --list-presets requires --spec", file=sys.stderr)
        return 2

    spec = load_json(spec_path)
    names = list_presets(spec)

    print("Available presets")
    print("-" * 80)
    if not names:
        print("(none)")
        return 0

    for name in names:
        print(name)
    return 0


def _run_analyzer(argv: list[str] | None = None) -> int:
    """Run the universal transmission analyzer workflow."""
    parser = build_parser()
    ns = parser.parse_args(argv)

    if ns.list_presets:
        return _print_presets(ns.spec_path)

    try:
        req = RunRequest(
            spec_path=ns.spec_path,
            schedule_path=ns.schedule_path,
            preset=ns.preset,
            state=ns.state,
            input_speed=ns.input_speed,
            show_speeds=bool(ns.show_speeds),
            ratios_only=bool(ns.ratios_only),
            show_topology=bool(ns.show_topology),
            as_json=bool(ns.as_json),
            output_json=ns.output_json,
            overrides=parse_key_value_overrides(ns.overrides),
        )

        app = TransmissionApplication()
        payload = app.run(req)

        if ns.as_json:
            print(json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False))
        else:
            print(
                render_text_report(
                    payload,
                    show_speeds=bool(ns.show_speeds),
                    ratios_only=bool(ns.ratios_only),
                )
            )
        return 0

    except TransmissionAppError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    except FileNotFoundError as exc:
        print(f"ERROR: file not found: {exc}", file=sys.stderr)
        return 2
    except json.JSONDecodeError as exc:
        print(f"ERROR: invalid JSON: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:
        print(f"ERROR: unexpected failure: {exc}", file=sys.stderr)
        return 1


def main(argv: list[str] | None = None) -> int:
    """Run the transmissions command-line interface."""
    args = list(sys.argv[1:] if argv is None else argv)

    if args and args[0] == "sphinx-skel":
        return _run_sphinx_skel(args[1:])

    return _run_analyzer(args)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
