# Generated by transmissions.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> transmissions -> repository root
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

project = 'Gearsets - transmissions'
author = 'Gearsets'

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = ['dearpygui', 'dearpygui.dearpygui', 'matplotlib', 'matplotlib.pyplot', 'numpy', 'pandas', 'plotly', 'plotly.graph_objects', 'rich', 'rich.console', 'rich.panel', 'rich.table', 'rich.text', 'scipy', 'scipy.linalg', 'scipy.optimize', 'sympy']
napoleon_google_docstring = True
napoleon_numpy_docstring = True
